[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  GIT_SUBMODULES = "true"

[context.production.environment]
  GIT_SUBMODULES = "true"

[[redirects]]
  from = "/vymaz-si-pamatku"
  to = "/vymaz-si-pamatku/index.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
